apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
  labels:
    app: todo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: kamranmiadi/todo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-backend-config
              key: APP_PORT
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: todo-backend-config
              key: DB_URL
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-backend-secret
              key: DB_PASSWORD