apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
          secretKeyRef:
            name: todo-backend-secret
            key: DB_PASSWORD
      volumeMounts:
      - name: mongodb-storage
        mountPath: /data/db
        volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc